/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-12-13 10:23:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class add_002dpromotions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1765621324041L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add Promotion</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-50\">\r\n");
      out.write("    ");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
 String fullname=(String) session.getAttribute("fullname"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"bg-white shadow-lg border-b border-gray-200\">\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("      <div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("        <!-- Logo -->\r\n");
      out.write("        <a href=\"/servlet-jsp-gr3/home\" class=\"flex-shrink-0 flex items-center\">\r\n");
      out.write("          <span\r\n");
      out.write("            class=\"text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent\">IIT\r\n");
      out.write("            Store</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation Links -->\r\n");
      out.write("        <div class=\"hidden md:flex space-x-8\">\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/home\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Home</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/categories\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Categories</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/products\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Products</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/promotions\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Promotions</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- User Info -->\r\n");
      out.write("        ");
 if (fullname !=null) { 
      out.write("\r\n");
      out.write("          <div class=\"flex items-center space-x-4\">\r\n");
      out.write("            <span class=\"text-gray-700 font-semibold\">\r\n");
      out.write("              ");
      out.print( fullname );
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("            <a href=\"/servlet-jsp-gr3/logout\"\r\n");
      out.write("              class=\"bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200\">Logout</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          ");
 } else { 
      out.write("\r\n");
      out.write("            <a href=\"/servlet-jsp-gr3/login\"\r\n");
      out.write("              class=\"bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200\">Login</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Header Section -->\r\n");
      out.write("    <div class=\"bg-gradient-to-r from-orange-600 to-red-600 text-white py-12 mb-12\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center\">\r\n");
      out.write("            <h1 class=\"text-4xl font-bold mb-2\">Add New Promotion</h1>\r\n");
      out.write("            <p class=\"text-orange-100\">Create a promotional campaign to boost your sales</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Form Container -->\r\n");
      out.write("    <div class=\"max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 pb-12\">\r\n");
      out.write("        <div class=\"bg-white rounded-xl shadow-lg p-8\">\r\n");
      out.write("            <form action=\"/servlet-jsp-gr3/promotions?action=add\" method=\"post\" id=\"promotionForm\">\r\n");
      out.write("                \r\n");
      out.write("                <!-- Dates Section -->\r\n");
      out.write("                <div class=\"mb-8\">\r\n");
      out.write("                    <div class=\"flex items-center gap-3 mb-6 pb-4 border-b-2 border-gray-200\">\r\n");
      out.write("                        <div class=\"w-10 h-10 rounded-lg bg-gradient-to-r from-orange-600 to-red-600 flex items-center justify-center text-white\">\r\n");
      out.write("                            <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z\"></path>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-gray-800\">Promotion Dates</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <label class=\"block text-sm font-semibold text-gray-700 mb-2\">Start Date</label>\r\n");
      out.write("                            <input type=\"date\" name=\"dateDebut\" id=\"dateDebut\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <label class=\"block text-sm font-semibold text-gray-700 mb-2\">End Date</label>\r\n");
      out.write("                            <input type=\"date\" name=\"dateFin\" id=\"dateFin\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Discount Section -->\r\n");
      out.write("                <div class=\"mb-8\">\r\n");
      out.write("                    <div class=\"flex items-center gap-3 mb-6 pb-4 border-b-2 border-gray-200\">\r\n");
      out.write("                        <div class=\"w-10 h-10 rounded-lg bg-gradient-to-r from-orange-600 to-red-600 flex items-center justify-center text-white\">\r\n");
      out.write("                            <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-gray-800\">Discount Value</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"bg-gradient-to-br from-orange-50 to-red-50 rounded-lg p-8\">\r\n");
      out.write("                        <div class=\"text-center mb-6\">\r\n");
      out.write("                            <div class=\"text-5xl font-bold text-orange-600\" id=\"discountDisplay\">0</div>\r\n");
      out.write("                            <div class=\"text-lg text-gray-600\">Discount Percentage</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"mb-6\">\r\n");
      out.write("                            <input type=\"range\" name=\"promotionValeur\" id=\"promotionValeur\" min=\"0\" max=\"100\" value=\"0\" class=\"w-full h-3 bg-gray-300 rounded-lg appearance-none cursor-pointer accent-orange-600\" oninput=\"updateDiscountDisplay(this.value)\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"flex justify-between gap-2 mb-4\">\r\n");
      out.write("                            <button type=\"button\" onclick=\"setDiscount(5)\" class=\"px-3 py-2 bg-white border border-gray-300 rounded-lg hover:bg-orange-50 font-medium text-sm transition-colors\">5%</button>\r\n");
      out.write("                            <button type=\"button\" onclick=\"setDiscount(10)\" class=\"px-3 py-2 bg-white border border-gray-300 rounded-lg hover:bg-orange-50 font-medium text-sm transition-colors\">10%</button>\r\n");
      out.write("                            <button type=\"button\" onclick=\"setDiscount(15)\" class=\"px-3 py-2 bg-white border border-gray-300 rounded-lg hover:bg-orange-50 font-medium text-sm transition-colors\">15%</button>\r\n");
      out.write("                            <button type=\"button\" onclick=\"setDiscount(20)\" class=\"px-3 py-2 bg-white border border-gray-300 rounded-lg hover:bg-orange-50 font-medium text-sm transition-colors\">20%</button>\r\n");
      out.write("                            <button type=\"button\" onclick=\"setDiscount(30)\" class=\"px-3 py-2 bg-white border border-gray-300 rounded-lg hover:bg-orange-50 font-medium text-sm transition-colors\">30%</button>\r\n");
      out.write("                            <button type=\"button\" onclick=\"setDiscount(50)\" class=\"px-3 py-2 bg-white border border-gray-300 rounded-lg hover:bg-orange-50 font-medium text-sm transition-colors\">50%</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"text-center text-sm text-gray-600\">\r\n");
      out.write("                            <p>Drag the slider to set a custom discount value</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Action Buttons -->\r\n");
      out.write("                <div class=\"flex gap-3 justify-end pt-6 border-t border-gray-200\">\r\n");
      out.write("                    <a href=\"/servlet-jsp-gr3/promotions\" class=\"px-6 py-3 border border-gray-300 text-gray-700 font-semibold rounded-lg hover:bg-gray-50 transition-colors duration-200\">Cancel</a>\r\n");
      out.write("                    <button type=\"submit\" class=\"px-6 py-3 bg-gradient-to-r from-orange-600 to-red-600 text-white font-semibold rounded-lg hover:from-orange-700 hover:to-red-700 transition-all duration-200 shadow-lg\">Create Promotion</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function updateDiscountDisplay(value) {\r\n");
      out.write("            document.getElementById('discountDisplay').textContent = value;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function setDiscount(value) {\r\n");
      out.write("            document.getElementById('promotionValeur').value = value;\r\n");
      out.write("            updateDiscountDisplay(value);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("            document.getElementById('dateDebut').focus();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
