/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-12-13 10:23:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class add_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1765621324041L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1697023660423L));
    _jspx_dependants.put("jar:file:/D:/dev/soa/outils/Maven/Depot_local/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602870372000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <html lang=\"fr\">\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta charset=\"UTF-8\">\r\n");
      out.write("            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("            <title>Add Product</title>\r\n");
      out.write("            <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body class=\"bg-gray-50\">\r\n");
      out.write("            ");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
 String fullname=(String) session.getAttribute("fullname"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"bg-white shadow-lg border-b border-gray-200\">\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("      <div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("        <!-- Logo -->\r\n");
      out.write("        <a href=\"/servlet-jsp-gr3/home\" class=\"flex-shrink-0 flex items-center\">\r\n");
      out.write("          <span\r\n");
      out.write("            class=\"text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent\">IIT\r\n");
      out.write("            Store</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation Links -->\r\n");
      out.write("        <div class=\"hidden md:flex space-x-8\">\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/home\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Home</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/categories\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Categories</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/products\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Products</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/promotions\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Promotions</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- User Info -->\r\n");
      out.write("        ");
 if (fullname !=null) { 
      out.write("\r\n");
      out.write("          <div class=\"flex items-center space-x-4\">\r\n");
      out.write("            <span class=\"text-gray-700 font-semibold\">\r\n");
      out.write("              ");
      out.print( fullname );
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("            <a href=\"/servlet-jsp-gr3/logout\"\r\n");
      out.write("              class=\"bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200\">Logout</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          ");
 } else { 
      out.write("\r\n");
      out.write("            <a href=\"/servlet-jsp-gr3/login\"\r\n");
      out.write("              class=\"bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200\">Login</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Header Section -->\r\n");
      out.write("                <div class=\"bg-gradient-to-r from-purple-600 to-pink-600 text-white py-12 mb-12\">\r\n");
      out.write("                    <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center\">\r\n");
      out.write("                        <h1 class=\"text-4xl font-bold mb-2\">Add New Product</h1>\r\n");
      out.write("                        <p class=\"text-purple-100\">Create a new product in your catalog</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Form Container -->\r\n");
      out.write("                <div class=\"max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 pb-12\">\r\n");
      out.write("                    <div class=\"bg-white rounded-xl shadow-lg p-8\">\r\n");
      out.write("                        <form action=\"/servlet-jsp-gr3/products?action=add\" method=\"post\" id=\"productForm\">\r\n");
      out.write("                            <!-- Product Information Section -->\r\n");
      out.write("                            <div class=\"mb-8\">\r\n");
      out.write("                                <div class=\"flex items-center gap-3 mb-6 pb-4 border-b-2 border-gray-200\">\r\n");
      out.write("                                    <div\r\n");
      out.write("                                        class=\"w-10 h-10 rounded-lg bg-gradient-to-r from-purple-600 to-pink-600 flex items-center justify-center text-white\">\r\n");
      out.write("                                        <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("                                                d=\"M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z\">\r\n");
      out.write("                                            </path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h3 class=\"text-xl font-semibold text-gray-800\">Product Information</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Product Name -->\r\n");
      out.write("                                <div class=\"mb-6\">\r\n");
      out.write("                                    <label class=\"block text-sm font-semibold text-gray-700 mb-2\">Product Name</label>\r\n");
      out.write("                                    <input name=\"name\" id=\"name\" type=\"text\"\r\n");
      out.write("                                        class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent\"\r\n");
      out.write("                                        placeholder=\"Ex: Designer Chair\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Price -->\r\n");
      out.write("                                <div class=\"mb-6\">\r\n");
      out.write("                                    <label class=\"block text-sm font-semibold text-gray-700 mb-2\">Price (USD)</label>\r\n");
      out.write("                                    <div class=\"relative\">\r\n");
      out.write("                                        <span class=\"absolute left-4 top-3 text-gray-600 font-semibold\">$</span>\r\n");
      out.write("                                        <input name=\"price\" id=\"price\" type=\"number\" step=\"0.01\"\r\n");
      out.write("                                            class=\"w-full pl-8 pr-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent\"\r\n");
      out.write("                                            placeholder=\"0.00\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Category -->\r\n");
      out.write("                                <div class=\"mb-6\">\r\n");
      out.write("                                    <label class=\"block text-sm font-semibold text-gray-700 mb-2\">Category</label>\r\n");
      out.write("                                    <select name=\"categoryId\"\r\n");
      out.write("                                        class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent bg-white\">\r\n");
      out.write("                                        <option value=\"\">-- Select Category --</option>\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Description -->\r\n");
      out.write("                                <div class=\"mb-6\">\r\n");
      out.write("                                    <label class=\"block text-sm font-semibold text-gray-700 mb-2\">Description</label>\r\n");
      out.write("                                    <textarea name=\"description\" id=\"description\" rows=\"5\"\r\n");
      out.write("                                        class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none\"\r\n");
      out.write("                                        placeholder=\"Describe your product...\"></textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Action Buttons -->\r\n");
      out.write("                            <div class=\"flex gap-3 justify-end pt-6 border-t border-gray-200\">\r\n");
      out.write("                                <a href=\"/servlet-jsp-gr3/products?action=list\"\r\n");
      out.write("                                    class=\"px-6 py-3 border border-gray-300 text-gray-700 font-semibold rounded-lg hover:bg-gray-50 transition-colors duration-200\">Cancel</a>\r\n");
      out.write("                                <button type=\"submit\"\r\n");
      out.write("                                    class=\"px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white font-semibold rounded-lg hover:from-purple-700 hover:to-pink-700 transition-all duration-200 shadow-lg\">Create\r\n");
      out.write("                                    Product</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("                        document.getElementById('name').focus();\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /add-product.jsp(67,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("cat");
    // /add-product.jsp(67,40) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/add-product.jsp(67,40) '${requestScope.categories}'",_jsp_getExpressionFactory().createValueExpression("${requestScope.categories}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <option value=\"${cat.id}\">${cat.name}</option>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
