/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-12-13 15:04:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1765637658109L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1697023660423L));
    _jspx_dependants.put("jar:file:/D:/dev/soa/outils/Maven/Depot_local/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602870372000L));
    _jspx_dependants.put("jar:file:/D:/dev/soa/outils/Maven/Depot_local/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602870372000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("                <!DOCTYPE html>\r\n");
      out.write("                <html lang=\"fr\">\r\n");
      out.write("\r\n");
      out.write("                <head>\r\n");
      out.write("                    <meta charset=\"UTF-8\">\r\n");
      out.write("                    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                    <title>IIT Store - Home</title>\r\n");
      out.write("                    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("                </head>\r\n");
      out.write("\r\n");
      out.write("                <body class=\"bg-gray-50\">\r\n");
      out.write("                    ");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"bg-white shadow-lg border-b border-gray-200\">\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("      <div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("        <!-- Logo -->\r\n");
      out.write("        <a href=\"/servlet-jsp-gr3/home\" class=\"flex-shrink-0 flex items-center\">\r\n");
      out.write("          <span\r\n");
      out.write("            class=\"text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent\">IIT\r\n");
      out.write("            Store</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation Links -->\r\n");
      out.write("        <div class=\"hidden md:flex space-x-8\">\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/home\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Home</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/categories\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Categories</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/products\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Products</a>\r\n");
      out.write("          <a href=\"/servlet-jsp-gr3/promotions\"\r\n");
      out.write("            class=\"text-gray-700 hover:text-purple-600 px-3 py-2 text-sm font-medium transition-colors duration-200\">Promotions</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- User Info -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- Hero Section -->\r\n");
      out.write("                        <div class=\"bg-gradient-to-r from-purple-600 via-pink-600 to-red-600 text-white\">\r\n");
      out.write("                            <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24\">\r\n");
      out.write("                                <div class=\"text-center max-w-3xl mx-auto\">\r\n");
      out.write("                                    <h1 class=\"text-5xl md:text-6xl font-bold mb-6\">Welcome to IIT Store</h1>\r\n");
      out.write("                                    <p class=\"text-xl md:text-2xl text-purple-100 mb-10\">Discover premium\r\n");
      out.write("                                        products\r\n");
      out.write("                                        with amazing\r\n");
      out.write("                                        discounts</p>\r\n");
      out.write("                                    <div class=\"flex flex-col sm:flex-row gap-4 justify-center\">\r\n");
      out.write("                                        <a href=\"/servlet-jsp-gr3/products\"\r\n");
      out.write("                                            class=\"bg-white text-purple-600 hover:bg-purple-50 px-8 py-3 rounded-lg font-bold text-lg transition-all duration-200 shadow-lg\">\r\n");
      out.write("                                            Shop Now\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <a href=\"/servlet-jsp-gr3/promotions\"\r\n");
      out.write("                                            class=\"border-2 border-white text-white hover:bg-white hover:text-purple-600 px-8 py-3 rounded-lg font-bold text-lg transition-all duration-200\">\r\n");
      out.write("                                            View Promotions\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Featured Categories Section -->\r\n");
      out.write("                        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16\">\r\n");
      out.write("                            <div class=\"text-center mb-12\">\r\n");
      out.write("                                <h2 class=\"text-4xl font-bold text-gray-800 mb-4\">Browse Categories</h2>\r\n");
      out.write("                                <p class=\"text-gray-600 text-lg\">Find what you're looking for in our carefully\r\n");
      out.write("                                    curated\r\n");
      out.write("                                    categories</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("                                <!-- Category Cards -->\r\n");
      out.write("                                <div\r\n");
      out.write("                                    class=\"bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1\">\r\n");
      out.write("                                    <div class=\"h-40 bg-gradient-to-br from-blue-400 to-blue-600\"></div>\r\n");
      out.write("                                    <div class=\"p-6\">\r\n");
      out.write("                                        <h3 class=\"text-2xl font-bold text-gray-800 mb-2\">Electronics</h3>\r\n");
      out.write("                                        <p class=\"text-gray-600 mb-4\">Latest gadgets and tech products</p>\r\n");
      out.write("                                        <a href=\"/servlet-jsp-gr3/categories\"\r\n");
      out.write("                                            class=\"inline-block text-blue-600 hover:text-blue-800 font-semibold\">Explore\r\n");
      out.write("                                            →</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div\r\n");
      out.write("                                    class=\"bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1\">\r\n");
      out.write("                                    <div class=\"h-40 bg-gradient-to-br from-green-400 to-green-600\"></div>\r\n");
      out.write("                                    <div class=\"p-6\">\r\n");
      out.write("                                        <h3 class=\"text-2xl font-bold text-gray-800 mb-2\">Home & Living</h3>\r\n");
      out.write("                                        <p class=\"text-gray-600 mb-4\">Quality furniture and home decor</p>\r\n");
      out.write("                                        <a href=\"/servlet-jsp-gr3/categories\"\r\n");
      out.write("                                            class=\"inline-block text-green-600 hover:text-green-800 font-semibold\">Explore\r\n");
      out.write("                                            →</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div\r\n");
      out.write("                                    class=\"bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1\">\r\n");
      out.write("                                    <div class=\"h-40 bg-gradient-to-br from-orange-400 to-orange-600\"></div>\r\n");
      out.write("                                    <div class=\"p-6\">\r\n");
      out.write("                                        <h3 class=\"text-2xl font-bold text-gray-800 mb-2\">Fashion</h3>\r\n");
      out.write("                                        <p class=\"text-gray-600 mb-4\">Trendy clothing and accessories</p>\r\n");
      out.write("                                        <a href=\"/servlet-jsp-gr3/categories\"\r\n");
      out.write("                                            class=\"inline-block text-orange-600 hover:text-orange-800 font-semibold\">Explore\r\n");
      out.write("                                            →</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Why Choose Us Section -->\r\n");
      out.write("                        <div class=\"bg-white py-16\">\r\n");
      out.write("                            <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("                                <div class=\"text-center mb-12\">\r\n");
      out.write("                                    <h2 class=\"text-4xl font-bold text-gray-800 mb-4\">Why Choose IIT Store?</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            class=\"w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4\">\r\n");
      out.write("                                            <svg class=\"w-8 h-8 text-purple-600\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("                                                viewBox=\"0 0 24 24\">\r\n");
      out.write("                                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("                                                    d=\"M13 10V3L4 14h7v7l9-11h-7z\"></path>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <h3 class=\"text-xl font-bold text-gray-800 mb-2\">Fast Shipping</h3>\r\n");
      out.write("                                        <p class=\"text-gray-600\">Quick delivery to your doorstep</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            class=\"w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4\">\r\n");
      out.write("                                            <svg class=\"w-8 h-8 text-green-600\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("                                                viewBox=\"0 0 24 24\">\r\n");
      out.write("                                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("                                                    d=\"M9 12l2 2 4-4m7 0a9 9 0 11-18 0 9 9 0 0118 0z\"></path>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <h3 class=\"text-xl font-bold text-gray-800 mb-2\">Quality Guaranteed</h3>\r\n");
      out.write("                                        <p class=\"text-gray-600\">All products are verified</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            class=\"w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4\">\r\n");
      out.write("                                            <svg class=\"w-8 h-8 text-blue-600\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("                                                viewBox=\"0 0 24 24\">\r\n");
      out.write("                                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("                                                    d=\"M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192l-3.536 3.536M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-5 0a4 4 0 11-8 0 4 4 0 018 0z\">\r\n");
      out.write("                                                </path>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <h3 class=\"text-xl font-bold text-gray-800 mb-2\">24/7 Support</h3>\r\n");
      out.write("                                        <p class=\"text-gray-600\">Customer service always available</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            class=\"w-16 h-16 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4\">\r\n");
      out.write("                                            <svg class=\"w-8 h-8 text-orange-600\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("                                                viewBox=\"0 0 24 24\">\r\n");
      out.write("                                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("                                                    d=\"M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z\">\r\n");
      out.write("                                                </path>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <h3 class=\"text-xl font-bold text-gray-800 mb-2\">Best Prices</h3>\r\n");
      out.write("                                        <p class=\"text-gray-600\">Competitive pricing guaranteed</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Call to Action Section -->\r\n");
      out.write("                        <div class=\"bg-gradient-to-r from-purple-600 to-pink-600 text-white py-16\">\r\n");
      out.write("                            <div class=\"max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center\">\r\n");
      out.write("                                <h2 class=\"text-4xl font-bold mb-6\">Ready to Shop?</h2>\r\n");
      out.write("                                <p class=\"text-xl mb-8 text-purple-100\">Browse our collection and find your\r\n");
      out.write("                                    favorite\r\n");
      out.write("                                    products\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <a href=\"/servlet-jsp-gr3/products\"\r\n");
      out.write("                                    class=\"inline-block bg-white text-purple-600 hover:bg-purple-50 px-8 py-4 rounded-lg font-bold text-lg transition-all duration-200 shadow-lg\">\r\n");
      out.write("                                    Start Shopping Now\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Footer -->\r\n");
      out.write("                        <footer class=\"bg-gray-800 text-gray-300 py-12\">\r\n");
      out.write("                            <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("                                <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8 mb-8\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h3 class=\"text-white font-bold text-lg mb-4\">IIT Store</h3>\r\n");
      out.write("                                        <p class=\"text-sm\">Your trusted online shopping destination for quality\r\n");
      out.write("                                            products at\r\n");
      out.write("                                            great prices.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h4 class=\"text-white font-bold mb-4\">Quick Links</h4>\r\n");
      out.write("                                        <ul class=\"space-y-2 text-sm\">\r\n");
      out.write("                                            <li><a href=\"/servlet-jsp-gr3/products\"\r\n");
      out.write("                                                    class=\"hover:text-white\">Products</a></li>\r\n");
      out.write("                                            <li><a href=\"/servlet-jsp-gr3/categories\"\r\n");
      out.write("                                                    class=\"hover:text-white\">Categories</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a href=\"/servlet-jsp-gr3/promotions\"\r\n");
      out.write("                                                    class=\"hover:text-white\">Promotions</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h4 class=\"text-white font-bold mb-4\">Contact</h4>\r\n");
      out.write("                                        <p class=\"text-sm\">Email: support@iitstore.com</p>\r\n");
      out.write("                                        <p class=\"text-sm\">Phone: +1 (555) 123-4567</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"border-t border-gray-700 pt-8 text-center text-sm\">\r\n");
      out.write("                                    <p>&copy; 2025 IIT Store. All rights reserved.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </footer>\r\n");
      out.write("                </body>\r\n");
      out.write("\r\n");
      out.write("                </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("          ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /navbar.jsp(28,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.fullname}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <div class=\"flex items-center space-x-4\">\r\n");
        out.write("              <span class=\"text-gray-700 font-semibold\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.fullname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\r\n");
        out.write("              <a href=\"/servlet-jsp-gr3/logout\"\r\n");
        out.write("                class=\"bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200\">Logout</a>\r\n");
        out.write("            </div>\r\n");
        out.write("          ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <a href=\"/servlet-jsp-gr3/login\"\r\n");
        out.write("              class=\"bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200\">Login</a>\r\n");
        out.write("          ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
